config/routes.rb
Imazing::Application.routes.draw do
  resources :product_images

  resources :search_suggestions

  resources :searches

  resources :overallcategories

  resources :modalities do
    resources :modtypes
  end

  resources :manufacturers

  resources :transactions

  devise_for :users
  resources :users

  resources :products do 
    resources :messages
  end

    resources :uploads

  resources :products do 
    get 'search'
  end
  
  resources :pictures

  resources :modtypemanufacturers, only: [:new, :create, :destroy]

  namespace :dynamic_select do
    get ':modality_id/modtypes', to: 'modtypes#indexfilter', as: 'modtypes'
    get ':modtype_id/manufacturers', to: 'manufacturers#indexfilter', as: 'manufacturers'
  end

   root 'home#index'

end

app/models/overallcategory.rb
class Overallcategory < ActiveRecord::Base
  has_many :products
end

app/controllers/overallcategories_controller.rb
class OverallcategoriesController < ApplicationController
  before_action :set_overallcategory, only: [:show, :edit, :update, :destroy]

  # GET /overallcategories
  # GET /overallcategories.json
  def index
    @overallcategories = Overallcategory.all
  end

  # GET /overallcategories/1
  # GET /overallcategories/1.json
  def show
  end

  # GET /overallcategories/new
  def new
    @overallcategory = Overallcategory.new
  end

  # GET /overallcategories/1/edit
  def edit
  end

  # POST /overallcategories
  # POST /overallcategories.json
  def create
    @overallcategory = Overallcategory.new(overallcategory_params)

    respond_to do |format|
      if @overallcategory.save
        format.html { redirect_to @overallcategory, notice: 'Overallcategory was successfully created.' }
        format.json { render action: 'show', status: :created, location: @overallcategory }
      else
        format.html { render action: 'new' }
        format.json { render json: @overallcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /overallcategories/1
  # PATCH/PUT /overallcategories/1.json
  def update
    respond_to do |format|
      if @overallcategory.update(overallcategory_params)
        format.html { redirect_to @overallcategory, notice: 'Overallcategory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @overallcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /overallcategories/1
  # DELETE /overallcategories/1.json
  def destroy
    @overallcategory.destroy
    respond_to do |format|
      format.html { redirect_to overallcategories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_overallcategory
      @overallcategory = Overallcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def overallcategory_params
      params.require(:overallcategory).permit(:name, :product_id)
    end
end

app/helpers/overallcategories_helper.rb
module OverallcategoriesHelper
end

app/views/overallcategories/_form.html.haml
= form_for @overallcategory do |f|
  - if @overallcategory.errors.any?
    #error_explanation
      %h2= "#{pluralize(@overallcategory.errors.count, "error")} prohibited this overallcategory from being saved:"
      %ul
        - @overallcategory.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/overallcategories/edit.html.haml
%h1 Editing overallcategory

= render 'form'

= link_to 'Show', @overallcategory
\|
= link_to 'Back', overallcategories_path

app/views/overallcategories/index.html.haml
%h1 Listing overallcategories

%table
  %tr
    %th Name
    %th Product
    %th
    %th
    %th

  - @overallcategories.each do |overallcategory|
    %tr
      %td= overallcategory.name
      %td= link_to 'Show', overallcategory
      %td= link_to 'Edit', edit_overallcategory_path(overallcategory)
      %td= link_to 'Destroy', overallcategory, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Overallcategory', new_overallcategory_path

app/views/overallcategories/new.html.haml
%h1 New overallcategory

= render 'form'

= link_to 'Back', overallcategories_path

app/views/overallcategories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @overallcategory.name
%p
  %b Products:
  = @overallcategory.products.count

= link_to 'Edit', edit_overallcategory_path(@overallcategory)
\|
= link_to 'Back', overallcategories_path