config/routes.rb
Imazing::Application.routes.draw do
  resources :product_images

  resources :search_suggestions

  resources :searches

  resources :overallcategories

  resources :modalities do
    resources :modtypes
  end

  resources :manufacturers

  resources :transactions

  devise_for :users
  resources :users

  resources :products do 
    resources :messages
  end

    resources :uploads

  resources :products do 
    get 'search'
  end
  
  resources :pictures

  resources :modtypemanufacturers, only: [:new, :create, :destroy]

  namespace :dynamic_select do
    get ':modality_id/modtypes', to: 'modtypes#indexfilter', as: 'modtypes'
    get ':modtype_id/manufacturers', to: 'manufacturers#indexfilter', as: 'manufacturers'
  end

   root 'home#index'

end

app/models/search.rb
class Search < ActiveRecord::Base

def products
  @products ||= find_products
end

=begin
def manufacturers
  products.manufacturer ||= find_products
end

def modalities
  products.modality_id ||= find_products
end

def modtypes
  products.modtypes ||= find_products
end
=end

private

def find_products
  Product.find(:all, :conditions => conditions)
end

#this is only searching modality_name
def keyword_conditions
(["(products.modality_name LIKE ?", "%#{keywords}%"] || ["products.modtype_name LIKE ?", "%#{keywords}%"] || ["products.manufacturer_name LIKE ?", "%#{keywords}%"]) unless keywords.blank?
#  ["products.keywords LIKE ?", "%#{keywords}%"] unless keywords.blank?
end

#def keyword_conditions
#  modality_conditions || modtype_conditions || manufacturer_conditions
#end


def modality_conditions
  ["products.modality_name LIKE ?", "%#{keywords}%"] unless keywords.blank?
end

def modtype_conditions
  ["products.modtype_name LIKE ?", "%#{keywords}%"] unless keywords.blank?
end

def manufacturer_conditions
  ["products.manufacturer_name LIKE ?", "%#{keywords}%"] unless keywords.blank?
end

def minimum_price_conditions
  ["products.price >= ?", minimum_price] unless minimum_price.blank?
end

def maximum_price_conditions
  ["products.price <= ?", maximum_price] unless maximum_price.blank?
end

def modtype_conditions
  ["products.modtype_id = ?", modtype_id] unless modtype_id.blank?
end

def manufacturer_conditions
  ["products.manufacturer_name = ?", manufacturer_id] unless manufacturer_id.blank?
end

def modality_conditions
  ["products.modality_name = ?", modality_id] unless modality_id.blank?
end

def overallcategory_conditions
  ["products.overallcategory_id = ?", overallcategory_id] unless overallcategory_id.blank?
end

def conditions
  [conditions_clauses.join(' AND '), *conditions_options]
end

def conditions_clauses
  conditions_parts.map { |condition| condition.first }
end

def conditions_options
  conditions_parts.map { |condition| condition[1..-1] }.flatten
end

def conditions_parts
  private_methods(false).grep(/_conditions$/).map { |m| send(m) }.compact
end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render action: 'show', status: :created, location: @search }
      else
        format.html { render action: 'new' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:keywords, :manufacturer_id, :modtype_id, :modality_id, :condition_id, :country_id, :region_id, :prefremovalmethod_id, :minimum_price, :maximum_price, :rating, :availabilitydate, :year, :dealertype, :hospitaltype, :orthopedictype, :imagingcentertype, :drofficetype, :urgenttype, :painmanagementtype, :veterinarytype, :chiropractictype, :podiatrytype, :dentaltype, :overallcategory_id)
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.haml
= form_for @search do |f|
  - if @search.errors.any?
    #error_explanation
      %h2= "#{pluralize(@search.errors.count, "error")} prohibited this search from being saved:"
      %ul
        - @search.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :keywords
    = f.text_field :keywords
  .field
  #overallcategorycreate
    = f.label :overallcategory
    = f.collection_select(:overallcategory_id, Overallcategory.all, :id, :name, options = {:include_blank => true})
  .modalitycreate
    = f.label :modality
    //= f.collection_select(:modality_id, Modality.all, :id, :name, options = {:include_blank => true}, html_options = { data: {dynamic_selectable_url: dynamic_select_modtypes_path(':modality_id'), dynamic_selectable_target: '#product_modtype_id'}})
  .field
    //= f.label :modtype
    //= f.collection_select(:modtype_id, @product.modality.try(:modtypes) || [], :id, :name, options = {:include_blank => true}, html_options = { data: {dynamic_selectable_url: dynamic_select_manufacturers_path(':modtype_id'), dynamic_selectable_target: '#product_manufacturer_id'}})
  .field
    //= f.label :manufacturer
    //= f.collection_select(:manufacturer_id, @product.modtype.try(:manufacturers) || [], :id, :name, :include_blank => true)
  .field
    = f.label :minimum_price
    = f.text_field :minimum_price
  .field
    = f.label :maximum_price
    = f.text_field :maximum_price
  .field
    //= f.label :condition_id
    //= f.number_field :condition_id
  .field
    //= f.label :country_id
    //= f.number_field :country_id
  .field
    //= f.label :region_id
    //= f.number_field :region_id
  .field
    //= f.label :prefremovalmethod_id
    //= f.number_field :prefremovalmethod_id
  .field
    //= f.label :rating
    //= f.number_field :rating
  .field
    //= f.label :availabilitydate
    //= f.date_select :availabilitydate, {:start_year => Time.now.year, :end_year => Time.now.year + 1}
  .field
    = f.label :year
    = f.date_select :year, {:start_year => Time.now.year, :end_year => Time.now.year - 40, :discard_day => true, :discard_month => true}, :selected => Time.now.year
  .field
    //= f.label :dealertype
    //= f.check_box :dealertype
  .field
    //= f.label :hospitaltype
    //= f.check_box :hospitaltype
  .field
    //= f.label :orthopedictype
    //= f.check_box :orthopedictype
  .field
    //= f.label :imagingcentertype
    //= f.check_box :imagingcentertype
  .field
    //= f.label :drofficetype
    //= f.check_box :drofficetype
  .field
    //= f.label :urgenttype
    //= f.check_box :urgenttype
  .field
    //= f.label :painmanagementtype
    //= f.check_box :painmanagementtype
  .field
    //= f.label :veterinarytype
    //= f.check_box :veterinarytype
  .field
    //= f.label :chiropractictype
    //= f.check_box :chiropractictype
  .field
    //= f.label :podiatrytype
    //= f.check_box :podiatrytype
  .field
    //= f.label :dentaltype
    //= f.check_box :dentaltype
  .actions
    = f.submit 'Search'

app/views/searches/edit.html.haml
%h1 Editing search

= render 'form'

= link_to 'Show', @search
\|
= link_to 'Back', searches_path

app/views/searches/index.html.haml
%h1 Listing searches

%table
  %tr
    %th Keywords
    %th Manufacturer
    %th Modtype
    %th Modality
    %th Condition
    %th Country
    %th Region
    %th Prefremovalmethod
    %th Minimum price
    %th Maximum price
    %th Rating
    %th Availabilitydate
    %th Year
    %th Dealertype
    %th Hospitaltype
    %th Orthopedictype
    %th Imagingcentertype
    %th Drofficetype
    %th Urgenttype
    %th Painmanagementtype
    %th Veterinarytype
    %th Chiropractictype
    %th Podiatrytype
    %th Dentaltype
    %th Overallcategory
    %th
    %th
    %th

  - @searches.each do |search|
    %tr
      %td= search.keywords
      %td= search.manufacturer_id
      %td= search.modtype_id
      %td= search.modality_id
      %td= search.condition_id
      %td= search.country_id
      %td= search.region_id
      %td= search.prefremovalmethod_id
      %td= search.minimum_price
      %td= search.maximum_price
      %td= search.rating
      %td= search.availabilitydate
      %td= search.year
      %td= search.dealertype
      %td= search.hospitaltype
      %td= search.orthopedictype
      %td= search.imagingcentertype
      %td= search.drofficetype
      %td= search.urgenttype
      %td= search.painmanagementtype
      %td= search.veterinarytype
      %td= search.chiropractictype
      %td= search.podiatrytype
      %td= search.dentaltype
      %td= search.overallcategory_id
      %td= link_to 'Show', search
      %td= link_to 'Edit', edit_search_path(search)
      %td= link_to 'Destroy', search, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Search', new_search_path

app/views/searches/new.html.haml
%h1 New search

= render 'form'

= link_to 'Back', searches_path

app/views/searches/show.html.haml
%p#notice= notice

= render :partial => @search.products

= link_to 'Edit', edit_search_path(@search)
\|
= link_to 'Back', searches_path