config/routes.rb
Imazing::Application.routes.draw do
  resources :product_images

  resources :search_suggestions

  resources :searches

  resources :overallcategories

  resources :modalities do
    resources :modtypes
  end

  resources :manufacturers

  resources :transactions

  devise_for :users
  resources :users

  resources :products do 
    resources :messages
  end

    resources :uploads

  resources :products do 
    get 'search'
  end
  
  resources :pictures

  resources :modtypemanufacturers, only: [:new, :create, :destroy]

  namespace :dynamic_select do
    get ':modality_id/modtypes', to: 'modtypes#indexfilter', as: 'modtypes'
    get ':modtype_id/manufacturers', to: 'manufacturers#indexfilter', as: 'manufacturers'
  end

   root 'home#index'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @transaction }
      else
        format.html { render action: 'new' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:prefremovalmethod, :sellremovalcost, :sellshipcost, :selldate, :selluser, :buyuser)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.haml
= form_for @transaction do |f|
  - if @transaction.errors.any?
    #error_explanation
      %h2= "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
      %ul
        - @transaction.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :prefremovalmethod
    = f.text_field :prefremovalmethod
  .field
    = f.label :sellremovalcost
    = f.text_field :sellremovalcost
  .field
    = f.label :sellshipcost
    = f.text_field :sellshipcost
  .field
    = f.label :selldate
    = f.time_select :selldate
  .field
    = f.label :selluser
    = f.number_field :selluser
  .field
    = f.label :buyuser
    = f.number_field :buyuser
  .actions
    = f.submit 'Save'

app/views/transactions/edit.html.haml
%h1 Editing transaction

= render 'form'

= link_to 'Show', @transaction
\|
= link_to 'Back', transactions_path

app/views/transactions/index.html.haml
%h1 Listing transactions

%table
  %tr
    %th Prefremovalmethod
    %th Sellremovalcost
    %th Sellshipcost
    %th Selldate
    %th Selluser
    %th Buyuser
    %th
    %th
    %th

  - @transactions.each do |transaction|
    %tr
      %td= transaction.prefremovalmethod
      %td= transaction.sellremovalcost
      %td= transaction.sellshipcost
      %td= transaction.selldate
      %td= transaction.selluser
      %td= transaction.buyuser
      %td= link_to 'Show', transaction
      %td= link_to 'Edit', edit_transaction_path(transaction)
      %td= link_to 'Destroy', transaction, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Transaction', new_transaction_path

app/views/transactions/new.html.haml
%h1 New transaction

= render 'form'

= link_to 'Back', transactions_path

app/views/transactions/show.html.haml
%p#notice= notice

%p
  %b Prefremovalmethod:
  = @transaction.prefremovalmethod
%p
  %b Sellremovalcost:
  = @transaction.sellremovalcost
%p
  %b Sellshipcost:
  = @transaction.sellshipcost
%p
  %b Selldate:
  = @transaction.selldate
%p
  %b Selluser:
  = @transaction.selluser
%p
  %b Buyuser:
  = @transaction.buyuser

= link_to 'Edit', edit_transaction_path(@transaction)
\|
= link_to 'Back', transactions_path