config/routes.rb
Imazing::Application.routes.draw do
  resources :product_images

  resources :search_suggestions

  resources :searches

  resources :overallcategories

  resources :modalities do
    resources :modtypes
  end

  resources :manufacturers

  resources :transactions

  devise_for :users
  resources :users

  resources :products do 
    resources :messages
  end

    resources :uploads

  resources :products do 
    get 'search'
  end
  
  resources :pictures

  resources :modtypemanufacturers, only: [:new, :create, :destroy]

  namespace :dynamic_select do
    get ':modality_id/modtypes', to: 'modtypes#indexfilter', as: 'modtypes'
    get ':modtype_id/manufacturers', to: 'manufacturers#indexfilter', as: 'manufacturers'
  end

   root 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  include UsersHelper
  include Filterable

  has_many :messages

  belongs_to :transaction
  belongs_to :user

  belongs_to :modality
  belongs_to :modtype
  belongs_to :manufacturer

  belongs_to :overallcategory

  has_many :pictures


  has_many :product_images, :class_name => "ProductImage"
  
  has_one :primary_photo, :class_name=> "ProductImage"

  has_many :uploads

  accepts_nested_attributes_for :uploads, :allow_destroy => true

  accepts_nested_attributes_for :product_images, :allow_destroy => true

  validates_presence_of :modality, :modtype, :manufacturer, :overallcategory, :year

#adding scopes to better filter results 
  scope :modality_id, -> (modality_id) { where modality_id: modality_id }
  scope :manufacturer_id, -> (manufacturer_id) { where manufacturer_id: manufacturer_id }
  scope :modtype_id, -> (modtype_id) { where modtype_id: modtype_id }

  include ApplicationHelper
# have to set inheritance column to nil to allow the use of attribute named 'type' with self.inheritance_column = nil
self.inheritance_column = nil

#should use sphynx instead for full text search
def self.search(search)
  if search
#    where('modtype_name LIKE ?', "%#{search}%")
    where("modtype_name LIKE ? OR manufacturer_name LIKE ? OR modality_name LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
  else
    scoped
  end
end

#  after_validation :geocode

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :owninguser, only: [:destroy]

  helper_method :sort_column, :sort_direction

  has_scope :modality_id
  has_scope :modtype_id
  has_scope :manufacturer_id

  # GET /products
  # GET /products.json
  def index
#    @products = Product.search(params[:search]).filter(params.slice(:modtype, :manufacturer, :modality)).order(sort_column + " " + sort_direction).paginate(:per_page =>20, :page => params[:page])

#below is the working search
#    @products = Product.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page =>20, :page => params[:page])
#    @products = Product.search(params[:search]).filter(params.slice(:modtype_id, :manufacturer_id, :modality_id)).order(sort_column + " " + sort_direction)
#    @products = Product.search(params[:search]).filter(params.slice(:modtype_id, :manufacturer_id, :modality_id)).order(sort_column + " " + sort_direction).paginate(:per_page =>20, :page => params[:page])

#    @products = Product.filter(params.slice(:modtype_id, :manufacturer_id, :modality_id)).order(sort_column + " " + sort_direction).paginate(:per_page =>20, :page => params[:page])

#setup for using has_scope with searching
##    @products = apply_scopes(Product).all.search(params[:search]).filter(params.slice(:modtype, :manufacturer, :modality)).order(sort_column + " " + sort_direction).paginate(:per_page =>20, :page => params[:page])
#setup to only use apply_scopes
    @myproducts = apply_scopes(Product).search(params[:search]).order(sort_column + " " + sort_direction)
    @products=@myproducts.paginate(:per_page =>20, :page => params[:page])

  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @user = User.find_by_id(current_user.id)
    @product = @user.products.new(product_params)
    @product.modality_name = @product.modality.name
    @product.modtype_name = @product.modtype.name
    @product.manufacturer_name = @product.manufacturer.name
    @product.overallcategory_name = @product.overallcategory.name
    #leaving 'if params[:images]' should work like 'if params[:images].exists?'
    #authorize @product have this if using cancan
    respond_to do |format|
      if @product.save
        #to handle multiple images
        #if params[:images]
         # params[:images].each do |image|
          #  @product.product_images.create(:image => image)
          #end
        #end
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    #authorize @product use this if using cancan
    respond_to do |format|
#      unless params[:images].nil?
#          params[:images].each do |image|
#          @product.product_images.create(:image => image)
#          @product.product_images << ProductImage.create(:image => image)
#           @product.product_images.build
#        end
#      end
      if @product.update(product_params)
        if params[:images]
          params[:images].each do |image|
            @product.product_images.create(:image => image)
          end
        end
        @product.modality_name = @product.modality.name
        @product.modtype_name = @product.modtype.name
        @product.manufacturer_name = @product.manufacturer.name
        @product.overallcategory_name = @product.overallcategory.name
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def update_modtypes
    @modality = Modality.find_by_id(params[:modality_id])
    respond_to do |format|
      format.js
    end
  end

  def search
    @products = Product.search params[:search]
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private

    def sort_column
      Product.column_names.include?(params[:sort]) ? params[:sort] : "overallcategory_id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

  def owninguser
    @product.user == current_user
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:manufacturer_id, :modtype_id, :modality_id, :whattype, :serial, :condition, :country, :region, :prefremovalmethod, :price, :message_id, :warranty, :rating, :listedon, :listeduntil, :autorenew, :availability, :availabilitydate, :user, :year, :dealertype, :hospitaltype, :orthopedictype, :imagingcentertype, :drofficetype, :urgenttype, :pain, :Managementtype, :veterinarytype, :chiropractictype, :podiatrytype, :painmanagementtype, :dentaltype, :transaction_id, :user_id, :overallcategory_id, :manufacturer_name, :modality_name, :modtype_name, :transaction_name, :user_name, :overallcategory_name, :product_images, :image, :product_images_attributes, uploads_attributes: [:upload])
    end

end

app/helpers/products_helper.rb
module ProductsHelper

  def myproduct(current_user)
    self.user == current_user
  end

end

app/views/products/_alsoimageform.html.erb
<%= form_for @product,  :html => { :multipart => true, :id => "fileupload"  } do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="input-group">
<div id="overallcategorycreate">
  <%= f.label :overallcategory %>
  <%= f.collection_select(:overallcategory_id, Overallcategory.all, :id, :name, options = {:include_blank => true}) %>
</div>
<div class="modalitycreate" id="modalitycreate">
  <%= f.label :modality %>
  <%= f.collection_select(:modality_id, Modality.all, :id, :name, options = {:include_blank => true}, html_options = { data: {dynamic_selectable_url: dynamic_select_modtypes_path(':modality_id'), dynamic_selectable_target: '#product_modtype_id'}}) %>
  <!--/ :include_blank can also be 'true' to just have a blank field instead of a string
  -->
  <!--/ :onchange => ("$('#modtypecreate').submit()"))
  -->
</div>
<div class="modtypecreate" id="modtypecreate">
  <%= f.label :modtype %>
  <%= f.collection_select(:modtype_id, @product.modality.try(:modtypes) || [], :id, :name, options = {:include_blank => true}, html_options = { data: {dynamic_selectable_url: dynamic_select_manufacturers_path(':modtype_id'), dynamic_selectable_target: '#product_manufacturer_id'}}) %>
</div>
<div class="manufacturercreate" id="manufacturercreate">
  <%= f.label :manufacturer %>
  <%= f.collection_select(:manufacturer_id, @product.modtype.try(:manufacturers) || [], :id, :name, :include_blank => true) %>
  <div class="field"></div>
  <%= f.label :serial %>
  <%= f.text_field :serial %>
</div>
<div class="field">
  <%= f.label :condition %>
  <%= f.text_field :condition %>
</div>
<div class="field">
  <%= f.label :country %>
  <%= f.country_code_select(:country, [[ 'United States', 'United States' ], [ 'Canada', 'Canada' ]]) %>
</div>
<div class="field">
  <%= f.label :region %>
  <%= f.text_field :region %>
</div>
<div class="field">
  <%= f.label :prefremovalmethod %>
  <%= f.text_field :prefremovalmethod %>
</div>
<div class="field">
  <%= f.label :price %>
  <%= f.text_field :price %>
</div>
<div class="field">
  <%= f.label :warranty %>
  <%= f.text_field :warranty %>
</div>
<div class="field">
  <%= f.label :listedon %>
  <%= f.date_select :listedon, {:start_year => Time.now.year, :end_year => Time.now.year + 1}, :selected => Time.now %>
</div>
<div class="field">
  <%= f.label :listeduntil %>
  <%= f.date_select :listeduntil, {:start_year => Time.now.year, :end_year => Time.now.year + 1} %>
</div>
<div class="field">
  <%= f.label :autorenew %>
  <%= f.check_box :autorenew %>
</div>
<div class="field">
  <%= f.label :availability %>
  <%= f.text_field :availability %>
</div>
<div class="field">
  <%= f.label :availabilitydate %>
  <%= f.date_select :availabilitydate, {:start_year => Time.now.year, :end_year => Time.now.year + 1} %>
</div>
<div class="field">
  <%= f.label :year %>
  <!--/commenting out date field since it is giving an error of "undefined method 'change' for 2006:Fixnum" I can't find where this is being called(outside of javascript, but nothing should be looking at this field there...)
  -->
  <%= f.date_select :year, {:start_year => Time.now.year - 40, :end_year => Time.now.year, :discard_day => true, :discard_month => true}, :selected => @product.year %>
</div>
<div class="usertype">
  <h2>What type of User are you?</h2>
  <ul>
    <li>
      Dealer/Broker
      <%= f.check_box :dealertype %>
    </li>
    <li class="divider"></li>
    <li>
      Hospital
      <%= f.check_box :hospitaltype %>
    </li>
    <li class="divider"></li>
    <li>
      Orthopedic
      <%= f.check_box :orthopedictype %>
    </li>
    <li class="divider"></li>
    <li>
      Imaging Center
      <%= f.check_box :imagingcentertype %>
    </li>
    <li class="divider"></li>
    <li>
      Dr Office
      <%= f.check_box :drofficetype %>
    </li>
    <li class="divider"></li>
    <li>
      Urgent Care
      <%= f.check_box :urgenttype %>
    </li>
    <li class="divider"></li>
    <li>
      Pain Management
      <%= f.check_box :painmanagementtype %>
    </li>
    <li class="divider"></li>
    <li>
      Vertinary
      <%= f.check_box :veterinarytype %>
    </li>
    <li class="divider"></li>
    <li>
      Chiropractic
      <%= f.check_box :chiropractictype %>
    </li>
    <li class="divider"></li>
    <li>
      Podiatry
      <%= f.check_box :podiatrytype %>
    </li>
    <li class="divider"></li>
    <li>
      Dental
      <%= f.check_box :dentaltype %>
    </li>
  </ul>
</div>
  <div class="row fileupload-buttonbar">
      <div class="span7"> 
        <span class="btn btn-success fileinput-button">
          <i class="glyphicon glyphicon-plus glyphicon-white"></i>
          <input type="file" class="form-control"  name="product[uploads_attributes][][upload]" multiple>Upload Images
        </span>
<br></br>
    <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
    </table>
        <button type="submit" class="btn btn-primary start" id="startbutton">
              <i class="glyphicon glyphicon-upload glyphicon-white"></i>
              <span>Add Product</span>
        </button>
      </div>
      
    </div>

</div>
 

<% end %>


<script>
    var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
    };
  </script>

  <!-- The template to display files available for upload -->
  <script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
      <td class="preview"><span class="fade"></span></td>
      <td class="name"><span>{%=file.name%}</span></td>
      <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
      {% if (file.error) { %}
      <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
      {% } else if (o.files.valid && !i) { %}
      <td>
        <div class="progress progress-success progress-striped active"><div class="bar progress-bar" style="width:0%;"></div></div>
      </td>
      <td class="start" style="display:none">{% if (!o.options.autoUpload) { %}
        <button class="btn btn-primary">
          <i class="icon-upload icon-white"></i>
          <span>{%=locale.fileupload.start%}</span>
        </button>
        {% } %}</td>
      {% } else { %}
      <td colspan="2"></td>
      {% } %}
      <td class="cancel">{% if (!i) { %}
        <button class="btn btn-warning" onclick="minus()">
          <i class="icon-ban-circle icon-white"></i>
          <span>{%=locale.fileupload.cancel%}</span>
        </button>
        {% } %}</td>
    </tr>
    {% } %}
  </script>
  <!-- The template to display files available for download -->
  <script id="template-download" type="text/x-tmpl">
    
  </script>

  <script type="text/javascript" charset="utf-8">
    var num_added = 0;
    var added = 0;
    var all_data = {};
    function minus() {
      num_added--;
    };
    function submit() {
      if (num_added == 0) {
        document.forms["fileupload"].submit();
      }
      
    };
    $(function () {

        $('#startbutton').click(function() {
          if (num_added == 0) {
            document.forms["fileupload"].submit();
          }

        });

        // Initialize the jQuery File Upload widget:
        $('#fileupload').fileupload({
          complete: function (e, data) {
            window.location = "<%= root_url %>";
        },
          singleFileUploads: false
        })  .bind('fileuploadadd', function (e, data) {num_added++;})
            .bind('fileuploadsubmit', function (e, data) {
             if(added < num_added)
                  {
                  if (added == 0)
                      all_data = data;
                  else
                      {
                      $.each(data['files'], function(i, file){
                      all_data['files'].push(file);
                      });
                      $.each(data['context'], function(i, context){
                      all_data['context'].push(context);
                      });
                      }
                  added++;
                  if (added == num_added)
                      {
                      added++;
                      all_data.submit();
                      }
                  return false;
              }
            })
            .bind('fileuploadsend', function (e, data) {num_added = 0; added = 0;});
            
        // 
        // Load existing files:
        $.getJSON($('#fileupload').prop('action'), function (files) {
          var fu = $('#fileupload').data('blueimpFileupload'), 
            template;
          fu._adjustMaxNumberOfFiles(-files.length);
          console.log(files);
          template = fu._renderDownload(files)
            .appendTo($('#fileupload .files'));
          // Force reflow:
          fu._reflow = fu._transition && template.length &&
            template[0].offsetWidth;
          template.addClass('in');
          $('#loading').remove();
        });

    });
  </script>

app/views/products/_form.html.haml
= form_for @product, :html => {:multipart => true} do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg
  #overallcategorycreate
    = f.label :overallcategory
    = f.collection_select(:overallcategory_id, Overallcategory.all, :id, :name, options = {:include_blank => true})
  #modalitycreate.modalitycreate
    = f.label :modality
    = f.collection_select(:modality_id, Modality.all, :id, :name, options = {:include_blank => true}, html_options = { data: {dynamic_selectable_url: dynamic_select_modtypes_path(':modality_id'), dynamic_selectable_target: '#product_modtype_id'}})
    // :include_blank can also be 'true' to just have a blank field instead of a string
    // :onchange => ("$('#modtypecreate').submit()"))
  #modtypecreate.modtypecreate
    = f.label :modtype
    = f.collection_select(:modtype_id, @product.modality.try(:modtypes) || [], :id, :name, options = {:include_blank => true}, html_options = { data: {dynamic_selectable_url: dynamic_select_manufacturers_path(':modtype_id'), dynamic_selectable_target: '#product_manufacturer_id'}})
  #manufacturercreate.manufacturercreate
    = f.label :manufacturer
    = f.collection_select(:manufacturer_id, @product.modtype.try(:manufacturers) || [], :id, :name, :include_blank => true)
  .field
    = f.label :primary_photo
    = render :partial => 'uploads/whatindex', :remote => true
    //= render :partial => @product.uploads, :locals => { :list => true }
    #new_image_creation
      //images[] returned to the product as an array. We use file_field_tag since images is not @product's attribute
      //= render "product_images/uploadimage"
      = file_field_tag "images[]", type: :file, multiple: true
    #current_images
    - if @product.try(:product_images)
      #photos_showing
        %ul= render :partial => @product.product_images, :locals => { :list => true }
    //= f.fields_for :product_images do |builder|
    //  = builder.file_field :image, :multiple => true
    //= render "photos/form"
  .field
    = f.label :serial
    = f.text_field :serial
  .field
    = f.label :condition
    = f.text_field :condition
  .field
    = f.label :country
    = f.country_code_select(:country, [[ 'United States', 'United States' ], [ 'Canada', 'Canada' ]])
  .field
    = f.label :region
    = f.text_field :region
  .field
    = f.label :prefremovalmethod
    = f.text_field :prefremovalmethod
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :warranty
    = f.text_field :warranty
  .field
    = f.label :listedon
    = f.date_select :listedon, {:start_year => Time.now.year, :end_year => Time.now.year + 1}, :selected => Time.now
  .field
    = f.label :listeduntil
    = f.date_select :listeduntil, {:start_year => Time.now.year, :end_year => Time.now.year + 1}
  .field
    = f.label :autorenew
    = f.check_box :autorenew
  .field
    = f.label :availability
    = f.text_field :availability
  .field
    = f.label :availabilitydate
    = f.date_select :availabilitydate, {:start_year => Time.now.year, :end_year => Time.now.year + 1}
  .field
    = f.label :year
    //commenting out date field since it is giving an error of "undefined method 'change' for 2006:Fixnum" I can't find where this is being called(outside of javascript, but nothing should be looking at this field there...)
    //= f.date_select :year, {:start_year => Time.now.year - 40, :end_year => Time.now.year, :discard_day => true, :discard_month => true}, :selected => @product.year
  %div.usertype
    %h2 What type of User are you?
    %ul
      %li
        Dealer/Broker
        = f.check_box :dealertype
      %li{:class=>"divider"}
      %li
        Hospital
        = f.check_box :hospitaltype
      %li{:class=>"divider"}
      %li
        Orthopedic
        = f.check_box :orthopedictype
      %li{:class=>"divider"}
      %li
        Imaging Center
        = f.check_box :imagingcentertype
      %li{:class=>"divider"}
      %li
        Dr Office
        = f.check_box :drofficetype
      %li{:class=>"divider"}
      %li
        Urgent Care
        = f.check_box :urgenttype
      %li{:class=>"divider"}
      %li
        Pain Management
        = f.check_box :painmanagementtype
      %li{:class=>"divider"}
      %li
        Vertinary
        = f.check_box :veterinarytype
      %li{:class=>"divider"}
      %li
        Chiropractic
        = f.check_box :chiropractictype
      %li{:class=>"divider"}
      %li
        Podiatry
        = f.check_box :podiatrytype
      %li{:class=>"divider"}
      %li
        Dental
        = f.check_box :dentaltype
  .actions
    = f.submit 'Save'

app/views/products/_left_product_categories.html.haml
%label :overallcategory
.modalitycreate
  %label :modality
  = collection_select(:product, :modality_id, @products.modality_id, :id, :name, options = {:include_blank => true}

app/views/products/_product_mail.html.haml
= div_for product do
  %li
    = link_to "Product", product_path(product, :only_path => false)
    |
    |
    Product ID
    = product.id
    |
    = link_to 'Show', product_path(product, :only_path => false)
    |
    = link_to 'Edit product', edit_product_path(product, :only_path => false)
    = link_to 'Remove product Record', product_path(product, :only_path => false), :method => :delete, :data => { :confirm => 'Are you sure?' }
    %br
    %div#productdiv

app/views/products/_productfilterscheckbox.html.haml
%label Modality
- @myproducts.to_a.uniq{|product| product.modality_id}.each do |product|
  = product.modality_name
  = check_box_tag("modality_id", product.modality_id, nil)  
  //= product.check_box(:modality_id, "modality_id", nil)
%label Modtype
- @myproducts.to_a.uniq{|product| product.modtype_id}.each do |product|
  = product.modtype_name
  = check_box_tag("modtype_id", product.modtype_id, nil)  
%label Manufacturer
- @myproducts.current_scope.to_a.uniq{|product| product.manufacturer_id}.each do |product|
  = product.manufacturer_name
  = check_box_tag("manufacturer_id", product.manufacturer_id, nil)

app/views/products/_search.html.haml
= form_tag( products_path, :method => 'get', :id => "search-form") do
  = text_field_tag :search, params[:search], :id => 'search_field'
  = submit_tag "Search", :name => nil
  //= link_to_function "Clear", "$('search_field').clear()"

app/views/products/create.js.haml
/* Replace the count of videos */
$("#resumevids_count").html("#{pluralize(@member.resumevids.count, 'Video')}");
/* add the created video */
$("#resumevids_test").html("#{escape_javascript(render(:partial=>@member.resumevids))}");
/* create new blank form */
$("#newcreated").html("#{escape_javascript(render(:partial=>'resumevids/form'))}")

app/views/products/index.html.haml
= form_tag products_path, :method => 'get', :id => "products_search" do
  #productfiltersdropdown.leftsidebarsearch
    = render 'productfiltersdropdown'
  #indexview
    %title Products
    %h1 Listing products
    = hidden_field_tag :direction, params[:direction]
    = hidden_field_tag :sort, params[:sort]
    %p
      = text_field_tag :search, params[:search]
      = submit_tag "Search", :name => nil
    #products= render 'products'
  %br
  = link_to 'New Product', new_product_path
  = debug(params) if Rails.env.development?

app/views/products/show.html.haml
%title Product Show View
%p#notice= notice
%p
  %b Manufacturer:
  = @product.manufacturer_name
%p
  %b Modality Type:
  = @product.modtype_name
%p
  %b OverallCategory
  = @product.overallcategory_name
%p
  %b Modality:
  = @product.modality_name
%p
  %b Manufacturer:
  = @product.manufacturer.name
%p
  %b Modality Type:
  = @product.modtype.name
%p
  %b OverallCategory
  = @product.overallcategory.name
%p
  %b Modality:
  = @product.modality.name
%p
  %b PHOTO COUNT
  = @product.uploads.count
  %b All Photos:
  = @product.uploads.each do |p|
    = image_tag p.upload.url(:small)
  %b later try with pictures below
#pictures
  - for picture in @product.pictures
    .picture
      = image_tag picture.image_url(:thumb) if picture.image?
      = picture.name
      %br
      = link_to "edit", edit_picture_path(picture)
      |
      = link_to "remove", picture, :confirm => 'Are you sure?', :method => :delete
%p
  //= link_to "Add a Painting", new_picture_path(:product_id => @product)
%p
  %b PHOTO COUNT
  = @product.pictures.count
%p
  %b Add Photo:
#pictures
  = render @product.pictures
.clear
= form_for Picture.new do |paint|
  = paint.label :image, "Upload pictures:"
  = paint.file_field :image, multiple: true, name: "picture[image]"
  %script#template-upload{type: "text/x-tmpl"}
    :cdata
      <div class="upload">
      {%=o.name%}
      <div class="progress"><div class="bar" style="width: 0%"></div></div>
      </div>
  //= render "pictures/form"
  //- if @product.try(:primary_photo) && @product.primary_photo.image_stored?
  //  = image_tag @product.primary_photo.image.thumb('120x90').url
  //= @product.primary_photo
%p
  %b Serial:
  = @product.serial
%p
  %b Condition:
  = @product.condition
%p
  %b Country:
  = @product.country
%p
  %b Region:
  = @product.region
%p
  %b Prefremovalmethod:
  = @product.prefremovalmethod
%p
  %b Price:
  = @product.price
%p
  %b Message:
  = @product.messages
%p
  %b Warranty:
  = @product.warranty
%p
  %b Rating:
  = @product.rating
%p
  %b Listedon:
  = @product.listedon
%p
  %b Listeduntil:
  = @product.listeduntil
%p
  %b Autorenew:
  = @product.autorenew
%p
  %b Availability:
  = @product.availability
%p
  %b Availabilitydate:
  = @product.availabilitydate
%p
  %b User:
  = @product.user
%p
  %b Year:
  = @product.year
%p
  %b Dealertype:
  = @product.dealertype
%p
  %b Hospitaltype:
  = @product.hospitaltype
%p
  %b Orthopedictype:
  = @product.orthopedictype
%p
  %b Imagingcentertype:
  = @product.imagingcentertype
%p
  %b Drofficetype:
  = @product.drofficetype
%p
  %b Urgenttype:
  = @product.urgenttype
%p
  %b Pain:
  = @product.painmanagementtype
%p
  %b Veterinarytype:
  = @product.veterinarytype
%p
  %b Chiropractictype:
  = @product.chiropractictype
%p
  %b Podiatrytype:
  = @product.podiatrytype
%p
  %b Dentaltype:
  = @product.dentaltype
- if user_signed_in?
  = render "messages/form"
-else
  You must sign in to send a message about this product
  = link_to "Sign in", user_session_path
%br
//= link_to 'Send A message about this product', new_product_message_path(:product_id => @product.id)
= link_to 'Edit', edit_product_path(@product)
\|
= link_to 'Back', products_path